GET-15 | Set up dj-rest-auth with social authentication support
getnshare/backend pull request #5
Opened 2021-12-30 00:24 UTC by Ifihan

2021-12-30 00:39 UTC, Lord-sarcastic requested changes
- Apps are being duplicated in your settings file
- Settings file is not formatted
- Arrange installed apps in the order:

# Django inbuilt apps
# third party apps
# custom apps

2021-12-30 14:36 UTC, Lord-sarcastic requested changes
In the file backend/backend/settings.py, we still have duplicated app labels. Please, fix

2021-12-30 15:17 UTC, Lord-sarcastic requested changes
Changed the default EMAIL_BACKEND to Django's email console backend. Back end throws an error when email is supposed to be sent to the user after account creation.

See [here](https://docs.djangoproject.com/en/4.0/topics/email/#console-backend)

2021-12-30 16:25 UTC, Lord-sarcastic requested changes

2021-12-30 16:25 UTC, Lord-sarcastic commented on backend/backend/urls.py
> +    path("auth/", include("dj_rest_auth.urls")),
Password reset throws a bug
![Screenshot from 2021-12-30 17-24-57](https://user-images.githubusercontent.com/33290249/147769900-e9973014-2ef9-4ff4-95f3-0071477ff906.png)

2021-12-31 10:29 UTC, Ifihan commented on backend/backend/urls.py
> +    path("auth/", include("dj_rest_auth.urls")),
Resolved the error

2021-12-31 13:21 UTC, Lord-sarcastic requested changes

2021-12-31 13:21 UTC, Lord-sarcastic commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
This URL pattern should be under the 'auth' path and not to stand alone. Also, `path` is not for regular expressions. You should use `re_path` instead.

2021-12-31 13:56 UTC, Ifihan commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
The reason I did it like that was because that was how it was stated in the doc - https://dj-rest-auth.readthedocs.io/en/latest/faq.html

2021-12-31 14:16 UTC, Lord-sarcastic commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
The usage of `path`? or the `auth` thing?

2021-12-31 14:18 UTC, Lord-sarcastic commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
![Screenshot from 2021-12-31 15-16-54](https://user-images.githubusercontent.com/33290249/147827765-fcbdc403-c33b-4aba-af05-f286ff1587f0.png)
I'm having this. And it's because you're trying to use regular expressions with `path` which does not support it. You use `re_path` whenever you're specifying regular expressions.

2021-12-31 14:31 UTC, Ifihan commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
> The usage of `path`? or the `auth` thing?

I don't get this

2021-12-31 14:32 UTC, Ifihan commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
> ![Screenshot from 2021-12-31 15-16-54](https://user-images.githubusercontent.com/33290249/147827765-fcbdc403-c33b-4aba-af05-f286ff1587f0.png) I'm having this. And it's because you're trying to use regular expressions with `path` which does not support it. You use `re_path` whenever you're specifying regular expressions.

I'd fix that. This warning didn't come up here

2021-12-31 14:42 UTC, Ifihan commented on backend/backend/urls.py
> +    path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
Fixed.

2021-12-31 15:15 UTC, Lord-sarcastic requested changes

2021-12-31 15:15 UTC, Lord-sarcastic commented on backend/backend/urls.py
> +    re_path(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
Place this under the `/auth` path. It is a URL related to authentication. The final URL should read `/auth/password...`

2021-12-31 15:24 UTC, Lord-sarcastic requested changes
![Screenshot from 2021-12-31 16-22-43](https://user-images.githubusercontent.com/33290249/147830301-102d0e09-5896-4f52-a664-aa2fcafa3f24.png)

You're referencing a template when we're dealing with a REST framework. Your path should be interfacing with dj-rest-auth and not allauth directly.

2021-12-31 16:54 UTC, Lord-sarcastic approved these changes

2021-12-31 16:54 UTC, merged