GET-21 | Create an endpoint for adding user emails to a waitlist
getnshare/backend pull request #9
Opened 2022-01-06 12:09 UTC by Ubaydah

2022-01-06 12:11 UTC, Lord-sarcastic requested changes
I can't find any tests here.

2022-01-08 11:01 UTC, Lord-sarcastic requested changes
- Sort your imports in the order specified in the [Contribution documentation on imports](https://github.com/getnshare/backend/blob/dev/CONTRIBUTIONS/STRUCTURE.md)
- Run linting on all your files

2022-01-08 11:23 UTC, Ubaydah commented on authentify/tests/test_views.py
> +        self.assertNotEquals(response.status_code, 201)
I wan do am sha but I no sabi how I go run am, will look into it sir

2022-01-09 15:07 UTC, Lord-sarcastic commented on authentify/serializers.py
> +class WaitlistSerializer(serializers.ModelSerializer):
Neat stuff here 🔥

2022-01-09 15:12 UTC, Lord-sarcastic requested changes
You're still having a linting problem

2022-01-09 15:12 UTC, Lord-sarcastic commented on authentify/serializers.py
> +        fields = ['id', 'email']
Frontend should not be specifying an ID an. Also, we want to avoid exposing an ID to the frontend. If we're exposing unique values or primary keys, we'll use UUIDs instead. A task will be created for this purpose.

2022-01-09 15:12 UTC, Lord-sarcastic commented on authentify/serializers.py
> +        user, created = Waitlist.objects.get_or_create(email=email)
Why the `user` as choice of variable name?

2022-01-09 15:12 UTC, Lord-sarcastic commented on authentify/serializers.py
> +        return user
Same here too. `user` is a not a good name for a variable such as this.

2022-01-09 15:12 UTC, Lord-sarcastic commented on authentify/tests/test_views.py
> +        self.assertEquals(response.status_code, 201)
Change the use of `assertEquals` to `assertEqual`. The former is already deprecated. The latter is the current convention.

2022-01-09 15:16 UTC, Lord-sarcastic requested changes

2022-01-09 15:16 UTC, Lord-sarcastic commented on authentify/tests/test_views.py
> +    def test_join_waitlist_cannot_save_duplicates(self):
Your test on the duplicates does not really cover the test case. You're not checking if duplicate emails are in the database or not. You're only checking if they are the same

2022-01-11 09:33 UTC, Lord-sarcastic requested changes
Nice job! Just that one addition

2022-01-11 09:33 UTC, Lord-sarcastic commented on authentify/tests/test_views.py
>          email_test = Waitlist.objects.get(id=1)
Reference it by the email itself and not the ID. IDs are not very reliable in tests. You don't know the order in which the tests will be run.

2022-01-11 17:00 UTC, Lord-sarcastic requested changes

2022-01-11 17:00 UTC, Lord-sarcastic commented on authentify/tests/test_views.py
> +        self.assertEqual(email_test.id, 1)
You're still referencing by ID. You should be referencing by email

2022-01-11 18:31 UTC, merged